#!/usr/bin/env python

Import("env")

# give parent environment access to godot-cpp bindings for types
env.Append(CPPPATH=["src/"])

env_squirrel = env.Clone()

env_squirrel.Append(CPPPATH=["squirrel/include/"])

# use double precision floats and 64-bit integers
env_squirrel.Append(CPPDEFINES=["SQUSEDOUBLE"])
env_squirrel.Append(CPPDEFINES=["_SQ64"])

sources = [
	"squirrel/squirrel/sqapi.cpp",
	"squirrel/squirrel/sqbaselib.cpp",
	"squirrel/squirrel/sqfuncstate.cpp",
	"squirrel/squirrel/sqdebug.cpp",
	"squirrel/squirrel/sqlexer.cpp",
	"squirrel/squirrel/sqobject.cpp",
	"squirrel/squirrel/sqcompiler.cpp",
	"squirrel/squirrel/sqstate.cpp",
	"squirrel/squirrel/sqtable.cpp",
	"squirrel/squirrel/sqvm.cpp",
	"squirrel/squirrel/sqclass.cpp",

	"squirrel/sqstdlib/sqstdblob.cpp",
	"squirrel/sqstdlib/sqstdio.cpp",
	"squirrel/sqstdlib/sqstdstream.cpp",
	"squirrel/sqstdlib/sqstdmath.cpp",
	"squirrel/sqstdlib/sqstdsystem.cpp",
	"squirrel/sqstdlib/sqstdstring.cpp",
	"squirrel/sqstdlib/sqstdaux.cpp",
	"squirrel/sqstdlib/sqstdrex.cpp",

	"src/godot_squirrel_internals.cpp",
	"src/godot_squirrel_memory.cpp",
	"src/godot_squirrel_register_types.cpp",
	"src/godot_squirrel_script.cpp",
	"src/godot_squirrel_vm.cpp",
]

squirrel_objects = [env_squirrel.SharedObject(file) for file in sources]

Return("squirrel_objects")
